//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsNewShared.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhatsNewShared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/div&gt;&lt;/details&gt;.
        /// </summary>
        internal static string ReportGroupEnd {
            get {
                return ResourceManager.GetString("ReportGroupEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;details&gt;&lt;summary&gt;Ten or more folders updated in {0} (click here to show/hide)&lt;/summary&gt;&lt;div class=&quot;repThick&quot;&gt;.
        /// </summary>
        internal static string ReportGroupStart {
            get {
                return ResourceManager.GetString("ReportGroupStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  ({0} files).
        /// </summary>
        internal static string ReportLineStrresCount {
            get {
                return ResourceManager.GetString("ReportLineStrresCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/div&gt;.
        /// </summary>
        internal static string ReportLineStrresEnd {
            get {
                return ResourceManager.GetString("ReportLineStrresEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;.
        /// </summary>
        internal static string ReportLineStrresPath {
            get {
                return ResourceManager.GetString("ReportLineStrresPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}.
        /// </summary>
        internal static string ReportLineStrresPathNoUrl {
            get {
                return ResourceManager.GetString("ReportLineStrresPathNoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;div class=&quot;repLine&quot; aria-haspopup=&quot;true&quot;&gt;&lt;div class=&quot;repDate&quot;&gt;{0}&lt;/div&gt; | {1}.
        /// </summary>
        internal static string ReportLineStrresStart {
            get {
                return ResourceManager.GetString("ReportLineStrresStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;div class=&quot;repLineSA&quot;&gt;&lt;div class=&quot;repDate&quot;&gt;{0}&lt;/div&gt; | {1}.
        /// </summary>
        internal static string ReportLineStrresStartShowAll {
            get {
                return ResourceManager.GetString("ReportLineStrresStartShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;div class=&quot;repLine&quot;&gt;. . .&lt;/div&gt;.
        /// </summary>
        internal static string ReportOverflow {
            get {
                return ResourceManager.GetString("ReportOverflow", resourceCulture);
            }
        }
    }
}
